### ISSUE TITLE
TypeError：scale_image_with_crop_padding（） missing 1 required positional argument :'crop_size'

### ISSUE THREAD

**Issue by longside** [sthalles/deeplab_v3#20]
When I run the command: _python test.py --model_id=16645_, it throws the # TypeError：scale_image_with_crop_padding（） missing 1 required positional argument :'crop_size'.
so where is the wrong thing?thx.

**Comment by sthalles** [comment]
It should work now.

**Comment by longside** [comment]
Thank u bro, but after everything is set correctly, it throws a new TypeError:'>' not supported between instances of 'NoneType' and 'int'.
Details:

Traceback (most recent call last):
  File "test.py", line 77, in <module>
    test_dataset = test_dataset.map(lambda image, annotation, image_shape: scale_image_with_crop_padding(image, annotation, image_shape, args.crop_size))
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 838, in map
    return MapDataset(self, map_func)
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1826, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 488, in add_to_graph
    self._create_definition_if_needed()
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 321, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 338, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1789, in tf_map_func
    ret = map_func(*nested_args)
  File "test.py", line 77, in <lambda>
    test_dataset = test_dataset.map(lambda image, annotation, image_shape: scale_image_with_crop_padding(image, annotation, image_shape, args.crop_size))
  File "/home/sunyajing/Documents/Deeplearning/deeplab_v3-master/preprocessing/read_data.py", line 98, in scale_image_with_crop_padding
    image_croped = tf.image.resize_image_with_crop_or_pad(image,crop_size,crop_size)
  File "/home/sunyajing/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/image_ops_impl.py", line 758, in resize_image_with_crop_or_pad
    assert_ops += _assert(target_width > 0, ValueError,
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by longside** [comment]
OH, add args:"crop_size" in data.json, i missed it .
