### ISSUE TITLE
tensor shape mismatch

### ISSUE THREAD

**Issue by Otsutsukii** [sthalles/deeplab_v3#32]
hello , after creating the custom tfrecord file i tried to run `train.py` but it gives me the following errors 
```
ResNet checkpoints file successfully found.
Tensoboard folder: ./tboard_logs\12028
2018-08-20 08:44:58.956467: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Model checkpoits for resnet_v2_50 restored!
Traceback (most recent call last):
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 34799360 values, but the requested shape has 8699840
         [[Node: annotation_reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32](DecodeRaw_1, annotation_reshape/shape)]]
         [[Node: IteratorGetNext = IteratorGetNext[_class=["loc:@map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3"], output_shapes=[[?,900,900,3], [?,900,900], [?], [?]], output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandle)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 190, in <module>
    handle: training_handle})
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\python3.6\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 34799360 values, but the requested shape has 8699840
         [[Node: annotation_reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32](DecodeRaw_1, annotation_reshape/shape)]]
         [[Node: IteratorGetNext = IteratorGetNext[_class=["loc:@map/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3"], output_shapes=[[?,900,900,3], [?,900,900], [?], [?]], output_types=[DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandle)]]```

**Comment by sthalles** [comment]
Make sure you created the dataset correctly.
